export { default as HeroSection } from './HeroSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as AboutSection } from './AboutSection'
export { default as HowItWorksContent } from './HowItWorksContent'
export { default as AcknowledgmentsContent } from './AcknowledgmentsContent'
